#!/usr/bin/env bash
# Ignore SC2086 as requested
# shellcheck disable=SC2086

get_subdomain_info() {
    local full_domain="$1"
    local subdomain="$2"

    record=$(dig ${subdomain}.${full_domain} +short | head -n1)
    if [ -n "$record" ]; then
        echo "The subdomain ${subdomain} is a A record and points to ${record}"
    else
        echo "No A record found for ${subdomain}.${full_domain}"
    fi
}

main() {
    domain="$1"
    subdomain="$2"

    if [ -z "$subdomain" ]; then
        for sub in www lb-01 web-01 web-02; do
            get_subdomain_info "$domain" "$sub"
        done
    else
        get_subdomain_info "$domain" "$subdomain"
    fi
}

main "$@"
